### ISSUE TITLE
测试集文件排列方式

### ISSUE THREAD

**Issue by jaycecd** [ypwhs/dogs_vs_cats#10]
您好，请问为什么测试文件不是按 1, 2, 3 排列，而是按1,10,100,1000,10000,10001？为什么前5个数是等比数列，而到了10000之后就是等差数列呢？为什么是用10000区分呢？

**Comment by ypwhs** [comment]
这与操作系统有关，你可以自己写类似 `['test/%d.jpg' % x for x in range(12500)]` 这样的代码。
