### ISSUE TITLE
关于keras中的nb_sample不存在问题

### ISSUE THREAD

**Issue by potatouncle** [ypwhs/dogs_vs_cats#13]
请问在keras2中，ImageDataGenerator().flow_from_generator.nb_sample不存在，应该如何解决？谢谢

**Comment by ypwhs** [comment]
第一句话就写了，本项目使用的 Keras 版本是1.2.2。如果你使用的是更高级的版本，可能会稍有参数变化。

一年前的代码了，只看思路就好，跑不好就查文档自己改，不仅 samples 改了，连 steps_per_epoch 也该了。
