### ISSUE TITLE
请教  关于ImageDataGenerator的用法

### ISSUE THREAD

**Issue by study-never-alone** [ypwhs/dogs_vs_cats#14]
ImageDataGenerator的作用不是为了增加数据量吗？ 那么为什么最后保存的h5文件中训练集还是只有25000？

**Comment by ypwhs** [comment]
这里仅仅是为了提取特征，不进行数据增强。

ImageDataGenerator可以进行数据增强，但是不是每一个用它的人都必须要做数据增强。
