### ISSUE TITLE
fit_generator steps

### ISSUE THREAD

**Issue by chunhui204** [ypwhs/dogs_vs_cats#17]
培文哥，好像fit_generator里第二个steps参数是指的是batch个数，而文档里用的总的样本数（nb_batch*batch_size）,相当于输出的数据是把源数据集用aug的方式扩充了batch_size倍，感觉steps写成nb_batch*扩充倍数更容易读者理解。

**Comment by maple123xx** [comment]
非常感谢，运行成功了。我把‘’，train_generator.nb_sample‘’删了，那么steps默认就变成len(generator)了，然后就可以运行了。非常感谢培文哥的代码和解答！！！

**Comment by jsxyhelu** [comment]
train_generator.nb_sample‘’删除后可以运行。

**Comment by ypwhs** [comment]
当时写这个代码的时候 fit_generator 的第二个参数是样本数，之后 Keras 将第二个参数改为了 steps，所以会有这样的误会，写的时候需要以你使用的版本的 API 文档为准。
