### ISSUE TITLE
请教一下预测图片之后的操作

### ISSUE THREAD

**Issue by helios741** [ypwhs/dogs_vs_cats#18]
![yx4q eu 90w_xe50m lytgx](https://user-images.githubusercontent.com/12036324/39222004-c25911e8-486c-11e8-9604-9897be2f66db.png)
这一段当预测之后为什么要进行这种操作呢？求指教

**Comment by ypwhs** [comment]
第一句参考论文公式
第二三句是典型的归一化操作
第四五句是让图片变得更好看的操作，可有可无

**Comment by helios741** [comment]
@ypwhs Resnet的论文？能发下论文地址不？

**Comment by ypwhs** [comment]
![image](https://user-images.githubusercontent.com/10473170/39222844-5c758e06-4871-11e8-9194-81529ee1d7a2.png)

**Comment by helios741** [comment]
@ypwhs 谢啦
