### ISSUE TITLE
release里面的特征资源下载不了

### ISSUE THREAD

**Issue by Statham-stone** [ypwhs/dogs_vs_cats#2]
如题，请问可否提供百度云或google drive的链接？

谢谢

**Comment by ypwhs** [comment]
请仔细阅读README。

**Comment by Statham-stone** [comment]
看到了，谢谢

-----------------------------------------------------------------------------------------------------------------

Best Regards,

Statham Stone | Harbin Institute of Technology

2017-04-07 9:34 GMT+08:00 杨培文 (Yang Peiwen) <notifications@github.com>:
