### ISSUE TITLE
为什么ResNet50没有加preprocess_input？

### ISSUE THREAD

**Issue by tre-pengxu** [ypwhs/dogs_vs_cats#20]
为什么ResNet50没有用preprocess_input,而InceptionV3和Xception需要？
write_gap(ResNet50, (224, 224))
write_gap(InceptionV3, (299, 299), inception_v3.preprocess_input)
write_gap(Xception, (299, 299), xception.preprocess_input)

**Comment by ypwhs** [comment]
因为之前写这个代码的时候 resnet50 的 preprocess_input 会出错，所以没有使用。

现在早就已经支持了，所以应当加上对应的预处理函数。
