### ISSUE TITLE
如何修改成多分类

### ISSUE THREAD

**Issue by vVVtreasure** [ypwhs/dogs_vs_cats#8]
前面数据按照gap.py生成
Found 102945 images belonging to 30 classes.
Found 11456 images belonging to 30 classes.

我想改成30分类，x = Dense(30, activation='softmax')(x)
但是model.fit(X_train, y_train, batch_size=8, nb_epoch=8, validation_split=0.2)出错
错误：ValueError: Error when checking model target: expected dense_1 to have shape (None, 30) but got array with shape (102945, 1)
######3##
我该如何修改shape（102945,1）为（102945，30）
希望得到你的帮助！
谢谢

**Comment by ypwhs** [comment]
模型没错，只是数据没做 one-hot 编码。

**Comment by vVVtreasure** [comment]
数据的写入应该没有问题吧？接下来我该做哪些工作，才可以改为多分类呢？
感谢您的帮助！

**Comment by ypwhs** [comment]
看文档呀。。。

https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py#L44-L45

**Comment by vVVtreasure** [comment]
感谢您的指导！谢谢！
